namespace Datacute.SourceGeneratorContext;

internal static class Templates
{
    private const string GeneratorNamespace = "Datacute.SourceGeneratorContext";
    private const string AttributeName = "SourceGeneratorContextAttribute";
    public const string AttributeFullyQualified = GeneratorNamespace + "." + AttributeName;

    public const string AutoGeneratedComment = /* language=c# */
        @"//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Datacute.SourceGeneratorContext.
// </auto-generated>
//------------------------------------------------------------------------------
";

    public const string ClassDocCommentsBegin = /* language=c# */
        @"{0}/// <summary>
{0}/// When this item is examined by a source generator...<br/><br/>
";

    public const string ClassDocCommentsSectionBegin = /* language=c# */
        @"{0}/// {1} contains:
{0}/// <list type=""table"">
{0}/// <listheader><term>Key</term><description>Value</description></listheader>
";

    public const string OptionsLine = /* language=c# */
        @"/// <item><term>{0}</term><description>{1}</description></item>
";

    public const string ClassDocCommentsSectionEnd = /* language=c# */
        @"{0}/// </list><br/>
";

    public const string ClassDocCommentsEnd = /* language=c# */
        @"{0}/// </summary>
";

    public static string EscapeStringForDocComments(string input) =>
        input.Replace("&", "&amp;")
            .Replace("<", "&lt;")
            .Replace(">", "&gt;")
            .Replace("\"", "&quot;")
            .Replace("'", "&apos;");
}